<?php
$pdf = new \Fuel\Core\FPDF();
$name=html_entity_decode($name);
$pos = strpos($name,"o-d");
if($pos !== false){
	$name = str_replace("o-d","O'd",strtolower($name));
}
$dir=html_entity_decode(base64_decode($dir));
$dir = str_replace("o-d","O'd",$dir);
$pdf->AddFont('Arial','','arial.php');
$title = 'DOCUMENTOS LEGALES LOPD: COLETILLA PARA E-MAIL';
$pdf->SetTitle($title);
$pdf->SetAuthor('Análisis y gestión de datos S.L.');
$pdf->SetMargins(20,15,20);
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('Arial','',12);
$pdf->Ln(5);
$pdf->SetFont('Arial','BU',15);
$pdf->MultiCell(0,10,strtoupper('coletilla para e-mails'),0,'C');
$pdf->Ln(15);
$pdf->SetFont('Arial','',11);
$pdf->MultiCell(0,10,'***************************************************************************************************************',0,'J');
$pdf->SetFont('Arial','BI',11);
$pdf->MultiCell(0,6,utf8_decode('Protección de datos:'),0,'J');
$pdf->SetFont('Arial','I',11);
$pdf->MultiCell(0,6,utf8_decode($name.', en cumplimiento de lo dispuesto por la Ley Orgánica 15/1999 de 13 de Diciembre, de Protección de Datos de Carácter Personal, y de lo dispuesto en Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, relativo a la protección de las personas físicas en lo que respecta al tratamiento de datos personales y a la libre circulación de estos datos, procede a informarle:'),0,'J');
$pdf->MultiCell(0,6,utf8_decode('Que el presente e-mail contiene o puede contener datos de carácter personal y que los datos de carácter personal que nos facilite por vía telemática podrán ser recogidos e incorporados a nuestros ficheros de datos, con el objeto de enviarle información que puede ser de su interés.'),0,'J');
$pdf->MultiCell(0,6,utf8_decode('Que '.$name.' ha implantado todas las medidas de seguridad exigidas por la normativa vigente en materia de protección de datos, y que no cederá los datos a terceros sin el consentimiento previo del interesado.'),0,'J');
$pdf->MultiCell(0,6,utf8_decode('Que el interesado podrá ejercitar en todo momento los derechos de acceso, rectificación o supresión, o la limitación de su tratamiento, o a oponerse al mismo, dirigiéndose por escrito a nuestra sede situada en '.$dir.'.'),0,'J');$pdf->Ln(2.5);
$pdf->SetFont('Arial','BI',11);
$pdf->MultiCell(0,6,utf8_decode('Confidencialidad:'),0,'J');
$pdf->SetFont('Arial','I',11);
$pdf->MultiCell(0,6,utf8_decode('La información contenida en este mensaje y/o archivos adjuntos es confidencial y/o legalmente protegida y está destinada a ser leída exclusivamente por los destinatarios especificados. Si por error usted ha recibido esta comunicación y no es el destinatario señalado, le informamos que está totalmente prohibida, y es ilegal conforme al Código Penal, cualquier uso, revelación, distribución, impresión o copia de toda o alguna parte de la información contenida en esta comunicación, y le rogamos nos la reenvíe y la elimine de sus archivos. Gracias.'),0,'J');$pdf->Ln(1.5);
$pdf->MultiCell(0,6,utf8_decode('Si ha recibido este mensaje por error, le rogamos nos lo notifique inmediatamente por esta misma vía y proceda a su eliminación.'),0,'J');$pdf->Ln(2.5);
$pdf->SetFont('Arial','BI',11);
$pdf->MultiCell(0,6,utf8_decode('Seguridad:'),0,'J');
$pdf->SetFont('Arial','I',11);
$pdf->MultiCell(0,6,utf8_decode('Aunque hemos tomado las medidas para asegurarnos que este correo electrónico y sus ficheros adjuntos estén libres de virus, le recomendamos que a efectos de mantener buenas prácticas de seguridad, el receptor debe asegurarse que este correo y sus ficheros adjuntos estén libres de virus. El emisor no garantiza la integridad y seguridad del presente correo, ni se responsabiliza de posibles perjuicios derivados de la captura, incorporaciones de virus o cualesquiera otras manipulaciones efectuadas por terceros.'),0,'J');$pdf->Ln(2.5);
$pdf->SetFont('Arial','BI',11);
$pdf->MultiCell(0,6,utf8_decode('Medio Ambiente:'),0,'J');
$pdf->SetFont('Arial','I',11);
$pdf->MultiCell(0,6,utf8_decode('No me imprimas si no es necesario. Protejamos el medio ambiente.'),0,'J');$pdf->Ln(2.5);
$pdf->MultiCell(0,10,'***************************************************************************************************************',0,'J');
$pdf->Ln(20);
$pdf->Output("Coletilla-emails-$name.pdf",'I');
