<?php
$pdf = new PDF_MC_Table();
$name=html_entity_decode($name);
$nombre_pres=html_entity_decode($pres->get('nombre'));
$pdf->AddFont('Arial','','arial.php');
$title = 'DECLARACIÓN DE NO DISPONER DE ACTA DE CONSTITUCIÓN';
$pdf->SetTitle(utf8_decode($title));
$pdf->SetAuthor('Análisis y gestión de datos S.L.');
$pdf->SetMargins(20,15,20);
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('Arial','BU',14);
$pdf->MultiCell(0,10,strtoupper(utf8_decode('declaración de no disponer de acta de constitución')),0,'C');
$pdf->Ln(20);
$pdf->SetFont('Arial','',11);
$pdf->MultiCell(0,10,utf8_decode('Yo, D./Dª. '.$nombre_pres.' con DNI '.$pres->get('dni').', en calidad de PRESIDENTE de la Comunidad de Propietarios '.$name.', con CIF '.$cif.', '),0,'J');
$pdf->Ln(15);
$pdf->SetFont('Arial','B',12);
$pdf->MultiCell(0,10,'ACREDITO',0,'C');
$pdf->Ln(10);
$pdf->SetFont('Arial','',11);
$pdf->MultiCell(0,10,utf8_decode('Que la Comunidad de Propietarios no dispone del Acta de Constitución de la Comunidad.'),0,'J');
$pdf->Ln(5);
$pdf->MultiCell(0,10,utf8_decode('Para que así conste, se firma la presente, en'),0,'J');
$pdf->Ln(5);
$pdf->MultiCell(0,10,'Sevilla, a '.date('d').' de '.getMes(date('m')).' de '.date('Y').'.',0,'R');
$pdf->Ln(25);
$pdf->MultiCell(0,10,utf8_decode('Fdo. D./Dª....................................                                        Fdo. D./Dª.....................................'),0,'C');
$pdf->MultiCell(0,10,'Presidente de la Comunidad                                                 Secretario de la Comunidad',0,'C');
$pdf->Output("NoActa-$name.pdf",'I');