<?php
$pdf = new PDF_MC_Table();
$name=html_entity_decode($name);
$dir=html_entity_decode($dir);
$pdf->AddFont('Arial','','arial.php');
$title = 'DOCUMENTOS LEGALES LOPD: SOLICITUD DE ACCESO AL FICHERO DE VIDEOVIGILANCIA';
$pdf->SetTitle($title);
$pdf->SetAuthor('Análisis y gestión de datos S.L.');
$pdf->SetMargins(20,15,20);
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('Arial','B',15);
$pdf->MultiCell(0,10,strtoupper('solicitud de acceso al fichero de videovigilancia'),0,'C');
$pdf->Ln(5);
$pdf->SetFont('Arial','B',11);
$pdf->MultiCell(0,10,'Solicitud a:',0,'J');
$pdf->Ln(5);
$pdf->MultiCell(0,6,'A/A:    '.utf8_decode(html_entity_decode($name)),0,'J');
$pdf->SetFont('Arial','',11);
$pdf->MultiCell(0,6,'           '.utf8_decode(html_entity_decode($afdir1)),0,'J');
$pdf->MultiCell(0,6,'           '.utf8_decode(html_entity_decode($afdir2)),0,'J');
$pdf->Ln(10);
$pdf->SetFont('Arial','B',11);
$pdf->MultiCell(0,10,mb_strtoupper('datos del solicitante:'),0,'J');
$pdf->SetFont('Arial','',11);
$pdf->MultiCell(0,6,utf8_decode('D/Dª .................................................................... mayor de edad, con D.N.I. nº ........................ (del que acompaño fotocopia), vecino de la Comunidad de Propietarios '.$name.', con domicilio en '.$dir.', por medio del presente escrito manifiesta su deseo de ejercer su derecho de acceso, de conformidad con el artículo 15 de la Ley Orgánica 15/1999, y los artículos 12 y 13 del Real Decreto 1332/94.'),0,'J');$pdf->Ln(2.5);
$pdf->SetFont('Arial','B',11);
$pdf->MultiCell(0,10,mb_strtoupper('solicita.-'),0,'J');
$pdf->SetFont('Arial','',11);
$pdf->MultiCell(0,6,utf8_decode('Que se me facilite gratuitamente el acceso al fichero de videovigilancia propiedad de la Comunidad de Propietarios arriba indicada, en el plazo máximo de 10 días a contar desde la recepción de esta solicitud, conforme a las siguientes especificaciones:'),0,'J');$pdf->Ln(2.5);
$pdf->Ln(5);
$pdf->SetWidths(array(85,85));
$pdf->SetAligns(array('L','L'));
$pdf->Row(array("\n  Fecha/s de grabación:\n\n\n","\n  Intervalo horario solicitado:\n\n\n"));
$pdf->SetWidths(array(170));
$pdf->SetAligns(array('L'));
$pdf->Row(array("\n  Medio o soporte para el envío de la información:\n\n    * Pen-drive facilitado por el solicitante   Sí O    No O\n\n    * E-mail: _________________________\n\n    * Otros: __________________________\n\n"));
$pdf->Row(array("\n  Motivo fundado que justifica esta solicitud:\n\n\n\n"));
$pdf->Ln(10);
$pdf->MultiCell(0,10,'En ..................................., a........... de............................. de 20.....',0,'J');

$pdf->Output("Solicitud-videovigilancia-$name.pdf",'I');